# -*- coding: utf-8 -*-
#
# Form implementation generated from reading ui file 'ToolUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

import os

from PyQt5 import QtCore, QtGui, QtWidgets
# 导入样式文件
from QSSwhite import QSS


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 540)
        MainWindow.setMinimumSize(QtCore.QSize(640, 540))
        MainWindow.setMaximumSize(QtCore.QSize(640, 540))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(9, 9, 621, 491))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_11.setGeometry(QtCore.QRect(30, 10, 535, 151))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.label_11 = QtWidgets.QLabel(self.groupBox_11)
        self.label_11.setGeometry(QtCore.QRect(40, 10, 491, 123))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_1)
        self.groupBox_12.setGeometry(QtCore.QRect(30, 180, 535, 251))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.label_4 = QtWidgets.QLabel(self.groupBox_12)
        self.label_4.setGeometry(QtCore.QRect(40, 30, 60, 24))
        self.label_4.setObjectName("label_4")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_1.setGeometry(QtCore.QRect(102, 30, 156, 24))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.radioButton_1 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_1.setGeometry(QtCore.QRect(270, 26, 110, 32))
        self.radioButton_1.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icon/e52d9567c015cdb440344305380739e7.png"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        self.radioButton_1.setIcon(icon)
        self.radioButton_1.setIconSize(QtCore.QSize(30, 30))
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_12)
        self.radioButton_2.setGeometry(QtCore.QRect(398, 26, 111, 32))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icon/b721a1c9956b6e836cbdb6c57691ef09.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.radioButton_2.setIcon(icon1)
        self.radioButton_2.setIconSize(QtCore.QSize(22, 22))
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton_1 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_1.setGeometry(QtCore.QRect(40, 70, 91, 30))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icon/ooopic_1494068712.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_1.setIcon(icon2)
        self.pushButton_1.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_1.setObjectName("pushButton_1")
        self.label_5 = QtWidgets.QLabel(self.groupBox_12)
        self.label_5.setGeometry(QtCore.QRect(160, 72, 71, 24))
        self.label_5.setObjectName("label_5")
        self.progressBar_1 = QtWidgets.QProgressBar(self.groupBox_12)
        self.progressBar_1.setGeometry(QtCore.QRect(240, 75, 250, 20))
        self.progressBar_1.setProperty("value", 0)
        self.progressBar_1.setObjectName("progressBar_1")
        self.textEdit_1 = QtWidgets.QTextEdit(self.groupBox_12)
        self.textEdit_1.setGeometry(QtCore.QRect(40, 120, 455, 121))
        self.textEdit_1.setObjectName("textEdit_1")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_21 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_21.setGeometry(QtCore.QRect(10, 160, 600, 291))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.groupBox_21.setFont(font)
        self.groupBox_21.setObjectName("groupBox_21")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_21)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 20, 531, 24))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_21)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 41, 24))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_21)
        self.label_7.setGeometry(QtCore.QRect(20, 255, 71, 24))
        self.label_7.setObjectName("label_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_21)
        self.pushButton_2.setGeometry(QtCore.QRect(500, 250, 91, 30))
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox_21)
        self.progressBar_2.setGeometry(QtCore.QRect(90, 255, 391, 20))
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setObjectName("progressBar_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_21)
        self.textEdit_2.setGeometry(QtCore.QRect(20, 55, 571, 181))
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setTextInteractionFlags(
            QtCore.Qt.TextSelectableByKeyboard | QtCore.Qt.TextSelectableByMouse)
        self.textEdit_2.setObjectName("textEdit_2")
        self.groupBox_22 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_22.setGeometry(QtCore.QRect(10, 10, 451, 140))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.groupBox_22.setFont(font)
        self.groupBox_22.setObjectName("groupBox_22")
        self.label_2 = QtWidgets.QLabel(self.groupBox_22)
        self.label_2.setGeometry(QtCore.QRect(20, 18, 441, 123))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_8.setGeometry(QtCore.QRect(470, 10, 140, 140))
        self.groupBox_8.setObjectName("groupBox_8")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_2.setGeometry(QtCore.QRect(15, 25, 120, 35))
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_5.setGeometry(QtCore.QRect(15, 60, 120, 35))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_8)
        self.checkBox_6.setGeometry(QtCore.QRect(15, 95, 120, 35))
        self.checkBox_6.setObjectName("checkBox_6")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_31 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_31.setGeometry(QtCore.QRect(10, 160, 600, 291))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.groupBox_31.setFont(font)
        self.groupBox_31.setObjectName("groupBox_31")
        self.progressBar_3 = QtWidgets.QProgressBar(self.groupBox_31)
        self.progressBar_3.setGeometry(QtCore.QRect(90, 255, 391, 20))
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setObjectName("progressBar_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_31)
        self.pushButton_3.setGeometry(QtCore.QRect(500, 250, 91, 30))
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_31)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 41, 24))
        self.label_8.setObjectName("label_8")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.groupBox_31)
        self.lineEdit_31.setGeometry(QtCore.QRect(60, 20, 531, 24))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.textEdit_3 = QtWidgets.QTextEdit(self.groupBox_31)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 55, 571, 181))
        self.textEdit_3.setTextInteractionFlags(
            QtCore.Qt.TextSelectableByKeyboard | QtCore.Qt.TextSelectableByMouse)
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_31)
        self.label_9.setGeometry(QtCore.QRect(20, 255, 71, 24))
        self.label_9.setObjectName("label_9")
        self.groupBox_32 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_32.setGeometry(QtCore.QRect(10, 10, 451, 140))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.groupBox_32.setFont(font)
        self.groupBox_32.setObjectName("groupBox_32")
        self.label_3 = QtWidgets.QLabel(self.groupBox_32)
        self.label_3.setGeometry(QtCore.QRect(20, 18, 441, 123))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_7.setGeometry(QtCore.QRect(470, 10, 140, 140))
        self.groupBox_7.setObjectName("groupBox_7")
        self.checkBox_openFolder = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_openFolder.setGeometry(QtCore.QRect(15, 25, 120, 35))
        self.checkBox_openFolder.setChecked(True)
        self.checkBox_openFolder.setObjectName("checkBox_openFolder")
        self.radioButton_theme1 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_theme1.setGeometry(QtCore.QRect(15, 60, 120, 35))
        self.radioButton_theme1.setChecked(True)
        self.radioButton_theme1.setObjectName("radioButton_theme1")
        self.radioButton_theme2 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_theme2.setGeometry(QtCore.QRect(15, 95, 120, 35))
        self.radioButton_theme2.setObjectName("radioButton_theme2")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 251, 441))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 20, 201, 131))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(140, 180, 91, 24))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 180, 121, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.pushButton_json = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_json.setGeometry(QtCore.QRect(10, 300, 221, 23))
        self.pushButton_json.setObjectName("pushButton_json")
        self.pushButton_excel = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_excel.setGeometry(QtCore.QRect(10, 340, 221, 23))
        self.pushButton_excel.setObjectName("pushButton_excel")
        self.pushButton_openFolder2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_openFolder2.setGeometry(QtCore.QRect(10, 240, 221, 23))
        self.pushButton_openFolder2.setObjectName("pushButton_openFolder2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(280, 10, 325, 441))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(30, 20, 271, 101))
        self.label_16.setObjectName("label_16")
        self.lineEdit_infoAV = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_infoAV.setGeometry(QtCore.QRect(80, 130, 121, 24))
        self.lineEdit_infoAV.setObjectName("lineEdit_infoAV")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(10, 130, 121, 24))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.pushButton_info = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_info.setGeometry(QtCore.QRect(220, 130, 95, 23))
        self.pushButton_info.setObjectName("pushButton_info")
        self.textEdit_info = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_info.setGeometry(QtCore.QRect(10, 170, 305, 261))
        self.textEdit_info.setObjectName("textEdit_info")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        self.menu_H = QtWidgets.QMenu(self.menubar)
        self.menu_H.setObjectName("menu_H")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpenfile = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Icon/2017522122222.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenfile.setIcon(icon3)
        self.actionOpenfile.setObjectName("actionOpenfile")
        self.actionQiut = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Icon/ooopic_1495455270.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQiut.setIcon(icon4)
        self.actionQiut.setObjectName("actionQiut")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Icon/201752212221.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon5)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAuthor = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Icon/2017522122216.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAuthor.setIcon(icon6)
        self.actionAuthor.setObjectName("actionAuthor")
        self.menu_F.addAction(self.actionOpenfile)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.actionQiut)
        self.menu_H.addAction(self.actionAbout)
        self.menu_H.addSeparator()
        self.menu_H.addAction(self.actionAuthor)
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "bili-creator-tools"))
        self.groupBox_11.setTitle(_translate("MainWindow", "操作流程"))
        self.label_11.setText(_translate("MainWindow",
                                         "<html><head/><body><p>未完成: 这个部分用来对接未来的AE模板, 会生成自动化中间件 </p>这个程序用于生成自动化AE的中间文件; 未完成先留个位置</p></body></html>"))
        self.groupBox_12.setTitle(_translate("MainWindow", "运行过程"))
        self.label_4.setText(_translate("MainWindow", "文件名："))
        self.radioButton_1.setText(_translate("MainWindow", "视频数据"))
        self.radioButton_2.setText(_translate("MainWindow", "排行榜"))
        self.pushButton_1.setText(_translate("MainWindow", "开始"))
        self.label_5.setText(_translate("MainWindow", "完成进度："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "自动化AE"))
        self.groupBox_21.setTitle(_translate("MainWindow", "运行过程"))
        self.label_6.setText(_translate("MainWindow", "av号："))
        self.label_7.setText(_translate("MainWindow", "完成进度："))
        self.pushButton_2.setText(_translate("MainWindow", "开始"))
        self.groupBox_22.setTitle(_translate("MainWindow", "操作流程"))
        self.label_2.setText(_translate("MainWindow",
                                        "<html><head/><body><p>1、程序运行可以下载b站视频, 最大到1080p, 输入多个av号用逗号分隔 "
                                        "</p><p>2、也可以直接黏贴视频网址下载, 一次一个(复制完整网址)</p>"
                                        "<p>3、直接贴网址的方式支持几乎所有主流视频网站, 比如说油管n站a站腾讯</p><p>"
                                        "4、视频会保存到软件目录下的/Video文件夹</p></body></html>"))
        self.groupBox_8.setTitle(_translate("MainWindow", "选项"))
        self.checkBox_2.setText(_translate("MainWindow", "完成后打开文件夹"))
        self.checkBox_5.setText(_translate("MainWindow", "下载弹幕(限b站)"))
        self.checkBox_6.setText(_translate("MainWindow", "合并分段(限b站)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "1080p视频下载"))
        self.groupBox_31.setTitle(_translate("MainWindow", "运行过程"))
        self.pushButton_3.setText(_translate("MainWindow", "开始"))
        self.label_8.setText(_translate("MainWindow", "av号："))
        self.label_9.setText(_translate("MainWindow", "完成进度："))
        self.groupBox_32.setTitle(_translate("MainWindow", "操作流程"))
        self.label_3.setText(_translate("MainWindow",
                                        "<html><head/><body><p>1、程序运行可以根据av号生成弹幕热度, 作为视频亮点的参考</p><p>2、在av号栏输入需要分析的av号, 用逗号分隔, 不用加上\"av\"</p><p>3、弹幕频率主要是用于时间较长的直播等, 对于3分钟内的短视频不适用</p><p>4、生成的图片会保存到软件目录下的/Graph文件夹</p></body></html>"))
        self.groupBox_7.setTitle(_translate("MainWindow", "选项"))
        self.checkBox_openFolder.setText(_translate("MainWindow", "完成后打开文件夹"))
        self.radioButton_theme1.setText(_translate("MainWindow", "样式1"))
        self.radioButton_theme2.setText(_translate("MainWindow", "样式2 (没做好)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "生成弹幕热度"))
        self.groupBox.setTitle(_translate("MainWindow", "复制av号到剪贴板"))
        self.label.setText(_translate("MainWindow", "把room.json放到软件目录下,\n"
                                                    "或者直接复制excel带av号的那一列\n"
                                                    "\n"
                                                    "可以用在视频下载或者生成弹幕热度\n"
                                                    "或者用在其他用途"))
        self.lineEdit_3.setText(_translate("MainWindow", "10"))
        self.label_10.setText(_translate("MainWindow", "生成数量: (前___个)"))

        self.pushButton_json.setText(_translate("MainWindow", "从room.json复制av号"))
        self.pushButton_excel.setText(_translate("MainWindow", "从data.xlsx复制av号(没做好)"))
        self.pushButton_openFolder2.setText(_translate("MainWindow", "打开文件夹"))
        self.groupBox_2.setTitle(_translate("MainWindow", "获取视频详细信息(没做好)"))
        self.label_16.setText(_translate("MainWindow", "可以用在视频下载或者生成弹幕热度<br>或者用在视频简介"))
        self.lineEdit_infoAV.setText(_translate("MainWindow", "1919810"))
        self.label_17.setText(_translate("MainWindow", "输入av号:"))
        self.pushButton_info.setText(_translate("MainWindow", "获取信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "其他"))
        self.menu_F.setTitle(_translate("MainWindow", "文件(F)"))
        self.menu_H.setTitle(_translate("MainWindow", "帮助(H)"))
        self.actionOpenfile.setText(_translate("MainWindow", "查看文件夹"))
        self.actionOpenfile.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionQiut.setText(_translate("MainWindow", "退出"))
        self.actionQiut.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "关于"))
        self.actionAuthor.setText(_translate("MainWindow", "作者"))

        # 设置提示语
        for each in [self.lineEdit_1, self.lineEdit_2, self.lineEdit_31]:
            each.setToolTip("温馨提示：请先确认文件是否存在！")
        # 设置鼠标样式和提示语
        for each in [self.pushButton_1, self.pushButton_2, self.pushButton_3]:
            each.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        # 添加样式风格
        self.mystyle()
        # 添加样式风格
        self.mystyle()

    def mystyle(self):
        qss = QSS()
        self.setStyleSheet(qss.White)


if __name__ == '__main__':
    import sys

    if hasattr(QtCore.Qt, 'AA_EnableHighDpiScaling'):
        QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)

    if hasattr(QtCore.Qt, 'AA_UseHighDpiPixmaps'):
        QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)
    os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
    app = QtWidgets.QApplication(sys.argv)

    myui = Ui_MainWindow()
    myui.show()
    sys.exit(app.exec_())
